---
SOrder:
    orderby:
        - 'order_date'
        - 'order_number'
    orderdir:
        - 'DESC'
        - 'DESC'
Activity:
    orderby:
        - 'enddate'
    orderdir:
        - 'ASC'

STItem:
    ClickInfo:
        fields:
            text1: 'MF Category'
            lead_time: 'Lead Time'
        methods:
            pickableBalance: 'Sales Stock'
