---
Activity:
    ModelOrder:
        enddate: 'ASC'

STItem:
    ClickInfo:
        fields:
            text1: 'MF Category'
            lead_time: 'Lead Time'
        methods:
            pickableBalance: 'Sales Stock'
